name: CMake Build and Test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake make

    - name: Configure CMake
      run: cmake -S . -DCURRENT_DEBUG_LEVEL=DEBUG

    - name: Build
      run: make

    - name: Run tests
      run: ctest
